/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/envoy.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hood.geometry}
        material={materials["Material.001"]}
        position={[-0.11, -0.629, -0.026]}
        scale={[1, 0.916, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.head.geometry}
        material={materials.Material}
        position={[0, 0.172, 0]}
        scale={[1.174, 1.067, 1.067]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material.001"]}
        position={[0, 0.328, 0]}
        scale={1.103}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        position={[1.27, -2.814, 0]}
        rotation={[0, 0, -1.403]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.002"]}
        position={[-0.073, -0.632, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.Material}
        position={[-0.132, 0, 0]}
        scale={[0.416, 1.559, 0.416]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials["Material.001"]}
        scale={[0.531, 1.992, 0.531]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material.002"]}
        position={[1.301, -2.814, 0]}
        rotation={[0, 0, -1.403]}
      />
    </group>
  );
}

useGLTF.preload("/envoy.glb");
